# vim: ft=dockerfile
FROM docker.io/nixos/nix:2.12.0 as linuxboot

WORKDIR /build
COPY . .
RUN nix build \
	--extra-experimental-features "nix-command flakes" \
	-L --out-link /out .#linux_linuxboot

FROM docker.io/library/ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt update && apt install -y \
	acpica-tools \
	binutils \
	bison \
	build-essential \
	bzip2 \
	coreutils \
	curl \
	flex \
	g++ \
	gcc \
	git \
	gnat \
	libc6-dev \
	libncurses5-dev \
	libx11-dev \
	libxext-dev \
	m4 \
	make \
	mono-devel \
	python-is-python3 \
	python3-distutils \
	python3-pip \
	python3.8-venv \
	rsync \
	zlib1g-dev

WORKDIR /build

RUN git clone --branch=4.18 --depth=1 https://review.coreboot.org/coreboot /build
RUN git submodule update --init

ARG crossgcc_arch
RUN make $crossgcc_arch CPUS=$(nproc)

# depthcharge dependencies
RUN apt install -y \
	libflashrom-dev \
	libssl-dev
RUN pip install kconfiglib

COPY misc/coreboot/build.bash build.bash

COPY --from=linuxboot /out/*Image .

CMD bash build.bash
