[package]
name = "homelab-ci"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.38.0"
flate2 = "1.0.35"
futures = "0.3.31"
tar = "0.4.43"
tokio = { version = "1.43.0", features = ["full"] }
