FROM docker.io/library/ubuntu:20.04

ARG crossgcc_arch=aarch64

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
RUN apt update && apt install -y \
	acpica-tools \
	binutils \
	bison \
	build-essential \
	bzip2 \
	coreutils \
	curl \
	curl \
	flex \
	g++ \
	gcc \
	git \
	git \
	gnat \
	libc6-dev \
	libncurses5-dev \
	libx11-dev \
	libxext-dev \
	m4 \
	make \
	mono-devel \
	python-is-python3 \
	python3-distutils \
	python3-pip \
	python3.8-venv \
	sudo \
	zlib1g-dev

RUN git clone --branch=4.18 --depth=1 https://review.coreboot.org/coreboot /build

WORKDIR /build

RUN make crossgcc-$crossgcc_arch CPUS=$(nproc)

CMD bash
