keys:
  - &jmbaur_pgp D4A0692874AA71B7F1281491BB8667EA7EB08143
  - &beetroot age1wsy0k8zvvkt4rfcyfa3lqr8m3z4rx6y0snar78amm5604y0mr9aqyanlvf
  - &rhubarb age1gr6ezp2sytvwh4arpw8xwmezx59x9evdfr86sfr9kcayp500hskse7cksq
  - &squash age1k0cthp9dy5xngnpjc4cjwp86h3fxyrgtuk6h2lzn39dgx3ap894saredq7
  - &celery age1qsxratlwc7cdrh6d0l7la0jf4dcnvmr6c28nneyegsx4czl3cu0sd9sg9y
  # TODO(jared): for when sops is compatible with age plugins
  # - &yubikey5cnfc age1yubikey1q20xxhpyk00m3ezajg3769jpmgwkvasq4dzutg75jq96fytnlcmxs9ltmga
  # - &yubikey5nfc age1yubikey1q0tf5gp52t3smx6zduwyjnurw4cgjlqdm58a9dj6430e8mtrfexfg586p8p
creation_rules:
  - path_regex: nixos-configurations/squash/secrets.yaml
    pgp: *jmbaur_pgp
    age: *squash
  - path_regex: nixos-configurations/rhubarb/secrets.yaml
    pgp: *jmbaur_pgp
    age: *rhubarb
  - path_regex: nixos-configurations/beetroot/secrets.yaml
    pgp: *jmbaur_pgp
    age: *beetroot
  - path_regex: nixos-configurations/celery/secrets.yaml
    pgp: *jmbaur_pgp
    age: *celery
  - pgp: *jmbaur_pgp # catch-all
# TODO(jared): for when sops is compatible with age plugins
#     - age:
#       - *yubikey5cnfc
#       - *yubikey5nfc
