theme = "native"

[[block]]
block = "battery"
interval = 10
format = "{percentage:6#100} {percentage} {time}"

[[block]]
block = "networkmanager"
on_click = "foot -e nmtui"
ap_format = "{ssid^10}"
# device_format = "{name} {ap} {ips}"
device_format = "{name} {ips}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%F %T"
