# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/8bddb414-4f1e-4836-b50c-6067992ebdaf";
      fsType = "ext4";
    };

  fileSystems."/kodi" =
    {
      device = "/storage";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/storage" =
    {
      device = "/dev/disk/by-uuid/694d9a0f-649b-4d1b-a63a-8860fedbebb0";
      fsType = "ext4";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/19908aa1-1a0e-4517-8a1f-173bd0ee28f0"; }];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
