# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/d8063802-74df-4bb6-9c49-31990a305378";
      fsType = "btrfs";
      options = [ "subvol=@" "noatime" "discard=async" "compress=zstd" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/982ae5ce-3090-4fad-8e3e-b0f3339387ee";

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/d8063802-74df-4bb6-9c49-31990a305378";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" "discard=async" "compress=zstd" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/d8063802-74df-4bb6-9c49-31990a305378";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" "discard=async" "compress=zstd" ];
    };

  fileSystems."/home/.snapshots" =
    {
      device = "/dev/disk/by-uuid/d8063802-74df-4bb6-9c49-31990a305378";
      fsType = "btrfs";
      options = [ "subvol=@home/.snapshots" "noatime" "discard=async" "compress=zstd" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/8B86-EBBD";
      fsType = "vfat";
    };

  swapDevices = [ ];
  zramSwap = {
    enable = true;
    swapDevices = 1;
  };

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
