[package]
name = "tinybar"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
chrono = "0.4.38"
dbus = "0.9.7"
nix = { version = "0.28.0", features = ["fs", "signal"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
dbus-codegen = "0.11.0"
