# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/7fdd5669-3ede-4a72-8ebe-6efc06c36f63";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.lan.useDHCP = lib.mkDefault true;
  # networking.interfaces.lan1.useDHCP = lib.mkDefault true;
  # networking.interfaces.lan2.useDHCP = lib.mkDefault true;
  # networking.interfaces.lan3.useDHCP = lib.mkDefault true;
  # networking.interfaces.lan4.useDHCP = lib.mkDefault true;
  # networking.interfaces.lan5.useDHCP = lib.mkDefault true;
  # networking.interfaces.lan6.useDHCP = lib.mkDefault true;
  # networking.interfaces.sfpplus.useDHCP = lib.mkDefault true;
  # networking.interfaces.wan.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlP1p1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
