# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/7bdaa893-23f2-43d0-b14e-676b1af96790";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/12ff8ac9-228d-42ab-9eb0-d8b3c21e5e2e";

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/7bdaa893-23f2-43d0-b14e-676b1af96790";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var" =
    {
      device = "/dev/disk/by-uuid/7bdaa893-23f2-43d0-b14e-676b1af96790";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/var/lib" =
    {
      device = "/dev/disk/by-uuid/09302e9e-9246-416f-ad2f-fce5c8d4b384";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/7bdaa893-23f2-43d0-b14e-676b1af96790";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/5A2B-677E";
      fsType = "vfat";
    };

  boot.initrd.luks.devices."cryptfast0".device = "/dev/disk/by-uuid/1dc19675-c7af-4a80-8f30-eab40bcf0df7";
  boot.initrd.luks.devices."cryptfast1".device = "/dev/disk/by-uuid/41e7644e-56e2-4773-b67a-5e3cc7c31f79";

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;
  # networking.interfaces.www.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
