[package]
name = "dookie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
clap-num = "1.0.2"
evdev = "0.12.1"
libc = "0.2.144"
