{ config, lib, pkgs, ... }: {
  options.hardware.chromebook.mediatek = lib.mkEnableOption "mediatek chromebook";
  config = lib.mkIf config.hardware.chromebook.mediatek {
    boot.kernelPackages = pkgs.linuxPackages_testing;
    boot.kernelPatches = [
      {
        name = "mediatek_support";
        patch = null;
        extraStructuredConfig = with lib.kernel; {
          AHCI_MTK = module;
          ARCH_MEDIATEK = yes;
          ARM_MEDIATEK_CCI_DEVFREQ = yes;
          ARM_MEDIATEK_CPUFREQ = yes;
          ARM_MEDIATEK_CPUFREQ_HW = module;
          BT_HCIBTUSB_MTK = yes;
          BT_MTK = module;
          BT_MTKSDIO = module;
          BT_MTKUART = module;
          COMMON_CLK_MEDIATEK = yes;
          COMMON_CLK_MT2712 = yes;
          COMMON_CLK_MT6765 = yes;
          COMMON_CLK_MT6779 = yes;
          COMMON_CLK_MT6779_AUDSYS = module;
          COMMON_CLK_MT6779_CAMSYS = module;
          COMMON_CLK_MT6779_IMGSYS = module;
          COMMON_CLK_MT6779_IPESYS = module;
          COMMON_CLK_MT6779_MFGCFG = module;
          COMMON_CLK_MT6779_MMSYS = module;
          COMMON_CLK_MT6779_VDECSYS = module;
          COMMON_CLK_MT6779_VENCSYS = module;
          COMMON_CLK_MT6795 = yes;
          COMMON_CLK_MT6795_MFGCFG = yes;
          COMMON_CLK_MT6795_MMSYS = yes;
          COMMON_CLK_MT6795_VDECSYS = yes;
          COMMON_CLK_MT6795_VENCSYS = yes;
          COMMON_CLK_MT6797 = yes;
          COMMON_CLK_MT7622 = yes;
          COMMON_CLK_MT7986 = yes;
          COMMON_CLK_MT7986_ETHSYS = yes;
          COMMON_CLK_MT8167 = yes;
          COMMON_CLK_MT8167_AUDSYS = yes;
          COMMON_CLK_MT8167_IMGSYS = yes;
          COMMON_CLK_MT8167_MFGCFG = yes;
          COMMON_CLK_MT8167_MMSYS = yes;
          COMMON_CLK_MT8167_VDECSYS = yes;
          COMMON_CLK_MT8173 = yes;
          COMMON_CLK_MT8173_MMSYS = yes;
          COMMON_CLK_MT8183 = yes;
          COMMON_CLK_MT8183_AUDIOSYS = yes;
          COMMON_CLK_MT8183_CAMSYS = yes;
          COMMON_CLK_MT8183_IMGSYS = yes;
          COMMON_CLK_MT8183_IPU_ADL = yes;
          COMMON_CLK_MT8183_IPU_CONN = yes;
          COMMON_CLK_MT8183_IPU_CORE0 = yes;
          COMMON_CLK_MT8183_IPU_CORE1 = yes;
          COMMON_CLK_MT8183_MFGCFG = yes;
          COMMON_CLK_MT8183_MMSYS = yes;
          COMMON_CLK_MT8183_VDECSYS = yes;
          COMMON_CLK_MT8183_VENCSYS = yes;
          COMMON_CLK_MT8186 = yes;
          COMMON_CLK_MT8192 = yes;
          COMMON_CLK_MT8195 = yes;
          COMMON_CLK_MT8365 = yes;
          COMMON_CLK_MT8365_APU = yes;
          COMMON_CLK_MT8365_CAM = yes;
          COMMON_CLK_MT8365_MFG = yes;
          COMMON_CLK_MT8365_MMSYS = yes;
          COMMON_CLK_MT8365_VDEC = yes;
          COMMON_CLK_MT8365_VENC = yes;
          COMMON_CLK_MT8516 = yes;
          DRM_MEDIATEK = yes;
          DRM_MEDIATEK_DP = module;
          DRM_MEDIATEK_HDMI = yes;
          DWMAC_MEDIATEK = module;
          EINT_MTK = yes;
          GNSS_MTK_SERIAL = module;
          HW_RANDOM_MTK = module;
          IR_MTK = module;
          KEYBOARD_MTK_PMIC = module;
          MEDIATEK_GE_PHY = module;
          MEDIATEK_MT6360_ADC = module;
          MEDIATEK_MT6577_AUXADC = yes;
          MEDIATEK_WATCHDOG = yes;
          MMC_MTK = yes;
          MTD_NAND_ECC_MEDIATEK = module;
          MTD_NAND_MTK = module;
          MTK_ADSP_IPC = yes;
          MTK_ADSP_MBOX = yes;
          MTK_CMDQ = yes;
          MTK_CMDQ_MBOX = yes;
          MTK_CQDMA = module;
          MTK_DEVAPC = module;
          MTK_HSDMA = module;
          MTK_INFRACFG = yes;
          MTK_IOMMU = yes;
          MTK_MMSYS = yes;
          MTK_PMIC_WRAP = yes;
          MTK_SCP = module;
          MTK_SCPSYS = yes;
          MTK_SCPSYS_PM_DOMAINS = yes;
          MTK_SMI = yes;
          MTK_SVS = yes;
          MTK_T7XX = module;
          MTK_THERMAL = yes;
          MTK_TIMER = yes;
          MTK_UART_APDMA = module;
          NET_DSA_TAG_MTK = module;
          NVMEM_MTK_EFUSE = yes;
          PCIE_MEDIATEK = yes;
          PCIE_MEDIATEK_GEN3 = module;
          PHY_MTK_DP = module;
          PHY_MTK_HDMI = yes;
          PHY_MTK_MIPI_DSI = yes;
          PHY_MTK_PCIE = module;
          PHY_MTK_TPHY = yes;
          PHY_MTK_UFS = yes;
          PHY_MTK_XSPHY = module;
          PINCTRL_MT2712 = yes;
          PINCTRL_MT6397 = yes;
          PINCTRL_MT6765 = yes;
          PINCTRL_MT6779 = yes;
          PINCTRL_MT6795 = yes;
          PINCTRL_MT6797 = yes;
          PINCTRL_MT7622 = yes;
          PINCTRL_MT7986 = yes;
          PINCTRL_MT8167 = yes;
          PINCTRL_MT8173 = yes;
          PINCTRL_MT8183 = yes;
          PINCTRL_MT8186 = yes;
          PINCTRL_MT8188 = yes;
          PINCTRL_MT8192 = yes;
          PINCTRL_MT8195 = yes;
          PINCTRL_MT8365 = yes;
          PINCTRL_MT8516 = yes;
          PINCTRL_MTK = yes;
          PINCTRL_MTK_MOORE = yes;
          PINCTRL_MTK_PARIS = yes;
          PINCTRL_MTK_V2 = yes;
          PWM_MEDIATEK = module;
          PWM_MTK_DISP = yes;
          RPMSG_MTK_SCP = module;
          SCSI_UFS_MEDIATEK = module;
          SND_SOC_MEDIATEK = yes;
          SND_SOC_MT2701 = module;
          SND_SOC_MT2701_CS42448 = module;
          SND_SOC_MT2701_WM8960 = module;
          SND_SOC_MT6797 = module;
          SND_SOC_MT6797_MT6351 = module;
          SND_SOC_MT8173 = yes;
          SND_SOC_MT8173_MAX98090 = module;
          SND_SOC_MT8173_RT5650 = yes;
          SND_SOC_MT8173_RT5650_RT5514 = yes;
          SND_SOC_MT8173_RT5650_RT5676 = yes;
          SND_SOC_MT8183 = yes;
          SND_SOC_MT8183_DA7219_MAX98357A = yes;
          SND_SOC_MT8183_MT6358_TS3A227E_MAX98357A = yes;
          SND_SOC_MT8186 = yes;
          SND_SOC_MT8186_MT6366_DA7219_MAX98357 = yes;
          SND_SOC_MT8186_MT6366_RT1019_RT5682S = yes;
          SND_SOC_MT8192 = yes;
          SND_SOC_MT8192_MT6359_RT1015_RT5682 = yes;
          SND_SOC_MT8195 = module;
          SND_SOC_MT8195_MT6359 = module;
          SND_SOC_MTK_BTCVSD = module;
          SND_SOC_SOF = module;
          SND_SOC_SOF_ACPI = module;
          SND_SOC_SOF_COMPRESS = yes;
          SND_SOC_SOF_IPC3 = yes;
          SND_SOC_SOF_MT8186 = module;
          SND_SOC_SOF_MT8195 = module;
          SND_SOC_SOF_MTK_COMMON = module;
          SND_SOC_SOF_MTK_TOPLEVEL = yes;
          SND_SOC_SOF_OF = yes;
          SND_SOC_SOF_OF_DEV = module;
          SND_SOC_SOF_PCI = module;
          SND_SOC_SOF_TOPLEVEL = yes;
          SND_SOC_SOF_XTENSA = module;
          SND_SOC_SPRD = module;
          SND_SOC_SPRD_MCDT = module;
          SPI_MTK_NOR = yes;
          SPI_MTK_SNFI = module;
          SPMI_MTK_PMIF = yes;
          USB_MUSB_MEDIATEK = module;
          USB_XHCI_MTK = yes;
          VIDEO_MEDIATEK_JPEG = module;
          VIDEO_MEDIATEK_MDP = module;
          VIDEO_MEDIATEK_MDP3 = module;
          VIDEO_MEDIATEK_VCODEC = module;
          VIDEO_MEDIATEK_VCODEC_SCP = yes;
          VIDEO_MEDIATEK_VCODEC_VPU = yes;
          VIDEO_MEDIATEK_VPU = yes;
          WLAN_VENDOR_MEDIATEK = yes;
        };
      }
      rec {
        name = "mt8192-asurada-regulators";
        patch = pkgs.fetchpatch {
          inherit name;
          url = "https://lore.kernel.org/lkml/20221102190611.283546-2-nfraprado@collabora.com/raw";
          sha256 = "sha256-SbF1l8QDNSxkh3FwN0AE4adx7Dxzddie3FFFD+YANT0=";
        };
      }
      rec {
        name = "mt8192-asurada-backlight";
        patch = pkgs.fetchpatch {
          inherit name;
          url = "https://lore.kernel.org/lkml/20221102190611.283546-3-nfraprado@collabora.com/raw";
          sha256 = "sha256-vOgc1JzWuMOC4y/Oa9FOSBa6LzRtVVnTBT91R+qgOKU=";
        };
      }
      rec {
        name = "mt8192-gpu";
        patch = pkgs.fetchpatch {
          inherit name;
          url = "https://gitlab.freedesktop.org/gfx-ci/linux/-/commit/3842f3a80e65.patch";
          sha256 = "sha256-TrrS7pYhKL2Cs0kFPEuOUQvTMgIvkd2j5f4uWJJuMH4=";
        };
      }
    ];
  };
}
