- hosts: 192.168.1.2
  become: yes
  tasks:
    - name: remove pve-enterprise repository
      apt_repository:
        repo: deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise
        state: absent
    - name: add pve-no-subscription repository
      apt_repository:
        repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
        state: present
    - name: check if IOMMU is enabled
      lineinfile:
        backup: yes
        path: /etc/default/grub
        state: absent
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*amd_iommu=on'
      check_mode: true
      register: grub_cmdline_check
      changed_when: false
    - name: enable IOMMU
      lineinfile:
        backrefs: true
        path: /etc/default/grub
        regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=".*)"$'
        line: '\1 amd_iommu=on"'
      when: grub_cmdline_check.found == 0
      notify:
        - update grub
        - reboot
    - name: apt upgrade
      apt:
        update_cache: yes
        upgrade: dist
    - name: install curl and jq
      apt:
        name: curl,jq
        state: present
    - name: download nixos 21.11
      get_url:
        url: https://channels.nixos.org/nixos-21.11/latest-nixos-minimal-x86_64-linux.iso
        dest: /var/lib/vz/template/iso/nixos-minimal-21.11-x86_64-linux.iso
        checksum: sha256:bcc26dfd483a1a568e250fcb0f3624c45748b0a5788b465bec073eba1073716c

  handlers:
    - name: update grub
      shell: update-grub
    - name: reboot
      reboot:
