---
- hosts: localhost
  tasks:
    - name: add tailscale gpg key
      become: yes
      apt_key:
        url: https://pkgs.tailscale.com/stable/ubuntu/focal.gpg
        state: present
    - name: add tailscale repo
      become: yes
      apt_repository:
        repo: deb https://pkgs.tailscale.com/stable/ubuntu focal main
        state: present
    - name: update cache
      become: yes
      apt:
        update_cache: yes
    - name: upgrade OS
      become: yes
      apt:
        upgrade: dist
    - name: install apt packages
      become: yes
      apt:
        name:
          - ansible
          - curl
          - diodon
          - fonts-firacode
          - git
          - iperf3
          - jq
          - kitty
          - mosh
          - python3-psutil # required by ansible dconf module
          - systemd-container
          - tailscale
          - tmux
          - vim-gtk3
    - name: install snap packages
      become: yes
      snap:
        name:
          - bitwarden
          - brave
          - chromium
          - discord
          - fractal
          - signal-desktop
          - spotify
          - zoom-client
    - name: install snap packages with --classic
      become: yes
      snap:
        classic: yes
        name:
          - code
          - slack
    - name: copy kitty config
      copy:
        src: kitty.conf
        dest: /home/jared/.config/kitty/kitty.conf
    - name: copy git config
      copy:
        src: gitconfig
        dest: /home/jared/.gitconfig
    - name: copy vimrc
      copy:
        src: vimrc
        dest: /home/jared/.vimrc
    - name: copy tmux.conf
      copy:
        src: tmux.conf
        dest: /home/jared/.tmux.conf
    - name: get kitty-themes
      git:
        repo: "https://github.com/dexpota/kitty-themes"
        dest: /home/jared/.config/kitty/kitty-themes
    - name: set emacs keybindings for UI
      dconf:
        key: "/org/gnome/desktop/interface/gtk-key-theme"
        value: "'Emacs'"
    - name: set control to override caps lock
      dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['ctrl:nocaps']"
    - name: diodon shortcut name
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
        value: "'diodon'"
    - name: diodon shortcut command
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
        value: "'diodon'"
    - name: diodon shortcut binding
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
        value: "'<Shift><Super>c'"
    - name: enable custom keybindings
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
        value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
