---
- hosts: localhost
  become: yes
  tasks:
    - name: update cache
      apt:
        update_cache: yes
    - name: upgrade OS
      apt:
        upgrade: dist
    - name: install some packages
      apt:
        name:
          - python3-psutil
          - git
          - tmux
          - vim-gtk3
          - jq
    - name: set emacs keybindings for UI
      dconf:
        key: "/org/gnome/desktop/interface/gtk-key-theme"
        value: "Emacs"
    - name: set control to override caps lock
      dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['ctrl:nocaps']"
