---
- hosts: localhost
  tasks:
    - name: update cache
      become: yes
      apt:
        update_cache: yes
    - name: upgrade OS
      become: yes
      apt:
        upgrade: dist
    - name: install apt packages
      become: yes
      apt:
        name:
          - ansible
          - git
          - jq
          - mosh
          - python3-psutil # required by ansible dconf module
          - tmux
          - vim-gtk3
    - name: install snap packages
      become: yes
      snap:
        name:
          - spotify
          - bitwarden
    - name: install snap packages with --classic
      become: yes
      snap:
        classic: yes
        name:
          - code
          - slack
    - name: set emacs keybindings for UI
      dconf:
        key: "/org/gnome/desktop/interface/gtk-key-theme"
        value: "'Emacs'"
    - name: set control to override caps lock
      dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['ctrl:nocaps']"
