FROM docker.io/library/ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
RUN apt update && apt install -y \
	acpica-tools \
	bc \
	bison \
	build-essential \
	cpio \
	device-tree-compiler \
	dosfstools \
	e2fsprogs \
	e2tools \
	flex \
	git \
	libssl-dev \
	mtools \
	p7zip \
	p7zip-full \
	parted \
	python3 \
	gcc-7 \
	rsync \
	squashfs-tools \
	u-boot-tools \
	unzip \
	vim-nox \
	wget

WORKDIR /build

RUN git config --global user.email builder
RUN git config --global user.name builder

RUN git clone --depth=1 --branch=master https://github.com/solidrun/cn913x_build /build
RUN git clone --branch=master https://github.com/ARM-software/arm-trusted-firmware.git /build/build/arm-trusted-firmware && cd /build/build/arm-trusted-firmware && git checkout 00ad74c7afe67b2ffaf08300710f18d3dafebb45 && cd -
RUN git clone --depth=1 --branch=mv-ddr-devel https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell.git /build/build/mv-ddr-marvell
RUN git clone --depth=1 --branch=v2019.10 git://git.denx.de/u-boot.git /build/build/u-boot

COPY build.bash build.bash

CMD bash build.bash
