FROM docker.io/library/ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
RUN apt update && apt install -y \
	acpica-tools \
	bc \
	bison \
	build-essential \
	cpio \
	device-tree-compiler \
	dosfstools \
	e2fsprogs \
	e2tools \
	flex \
	git \
	libssl-dev \
	mtools \
	p7zip \
	p7zip-full \
	parted \
	python3 \
	qemu-system-arm \
	rsync \
	squashfs-tools \
	sudo \
	u-boot-tools \
	unzip \
	vim \
	wget

WORKDIR /build

RUN useradd -m builder
RUN chown -R builder:builder /build

USER builder

RUN git config --global user.email builder
RUN git config --global user.name builder
RUN git clone --depth=1 https://github.com/solidrun/cn913x_build /build
COPY build.bash build.bash

CMD bash build.bash
