name: build-overlay-derivations
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use binary cache
        uses: cachix/cachix-action@v12
        with:
          name: jmbaur
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build all the things
        run: nix develop .\#ci --command sh -c "just build"
