name: build-overlay-derivations
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Use binary cache
        uses: cachix/cachix-action@v11
        with:
          name: jmbaur
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build all the things
        run: nix develop --command just build
