name: build-overlay-derivations
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Use binary cache
        uses: cachix/cachix-action@v11
        with:
          name: jmbaur
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
          echo "system-features = aarch64-linux arm-linux" | sudo tee -a /etc/nix/nix.conf
      - run: |
          nix build -L --option system aarch64-linux --extra-platforms aarch64-linux .\#linux_cn913x
