name: build-overlay-derivations
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Use binary cache
        uses: cachix/cachix-action@v11
        with:
          name: jmbaur
          signingKey: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: uraimo/run-on-arch-action@v2
        name: Run aarch64 builds
        id: build
        with:
          arch: aarch64
          distro: ubuntu_latest
          run: "nix build .#packages.aarch64-linux.linux_cn913x"
